### ISSUE TITLE
Pretrained models do not match the getmodel function

### ISSUE THREAD

**Issue by SiminMirzaei** [kskim-phd/CBCT-DENOISING-CAD#1]
Hi there, 

We have tested the pretrained models for the case of 2D and unfortunately none of them match the getmodel of this script: 2_external_keyslice_de.py 

Could you please share a model for denoising that matches the get model?

Regards, 
Simin

**Comment by LimChaeYeon1003** [comment]
Hello,

We have not uploaded the pretrained weights for the key-slice selector to our GitHub.

The reason is that we used the training weights for the key-slice selector from our internal dataset directly for inference on the external dataset.

Additionally, denoising was performed in advance using the ISTA-U-NET based model, and the key-slice selector was retrained on the denoised data only.

Therefore, we have not uploaded the pretrained weights for the key-slice selector separately.

For get_model, we are using the default weights for EfficientNet-b0, which is why our bash file option is set to EfficientNet. This ensures that the model automatically loads the weights.

Thank you.

Regards,
Lim
